# -*- coding: utf-8 -*-
"""COVID-19 RISK WITH IF STATEMENT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IRCEhunTp2lcsfLDdXrXC45KM4cAYdHM

**COVID-19 RISK WITH IF STATEMENT**
"""

age = input("Are you a cigarette addict older than 75 years old? Please answer Yes or No : ").title()
chronic = input("Do you have a severe chronic disease? Please answer Yes or No : ").title()
immune = input("Is your immune system too weak? Please answer Yes or No :").title()

if age == 'No':
    age = False
else:
    age = True
if chronic == 'No':
    chronic = False
else:
    chronic = True
if immune == 'No':
    immune = False
else:
    immune = True  

risk = age or chronic or immune                       

if risk == True:
     print("You are in risky group")
else :
     print("You are not in risky group")     
print(risk)